# Jekyll configuration

name: Ahkab
description: Open Source electronic circuit simulation in Python

# url is currently only used only for the RSS feed in feed.xml
url: https://ahkab.github.io

# baseurl will often be '', but for a project page on gh-pages, it needs to
# be the project name.
# *** IMPORTANT: If your local "jekyll serve" throws errors change this to '' or
#     run it like so: jekyll serve --baseurl=''
baseurl: /ahkab

# This can be '' to hide the Github nav button
github: 'ahkab/ahkab'

# Set this to your UA-# value, or '' to disable the block completely
gaaccount: 'UA-43456631-1'

# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus: ''
comments: false

permalink: "/:title"
paginate: 1

highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables"]

exclude: ['README.md', 'LICENSE']
